<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Version>0.1.0</Version>
    <Deterministic>true</Deterministic>
    <RhinoVersion>8.27.26019.16021</RhinoVersion>
  </PropertyGroup>
</Project>
