<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Midas\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.18.25100.11001" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProxyHelper\ProxyHelper.csproj" />
  </ItemGroup>

</Project>
