<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Midas\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.27.26019.16021" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProxyHelper\ProxyHelper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ETABSv1">
      <HintPath>C:\Program Files\Computers and Structures\ETABS 22\ETABSv1.dll</HintPath>
    </Reference>
    <Reference Include="SAP2000v1">
      <HintPath>C:\Program Files\Computers and Structures\SAP2000 26\SAP2000v1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
