<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<TargetExt>.gha</TargetExt>
		<NoWarn>NU1701;NETSDK1086</NoWarn>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<Platforms>AnyCPU;ARM32;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<!-- Specifies information for Assembly and Yak -->
		<Version>1.0</Version>
		<Title>Fem2Rhino.Grasshopper.Reading</Title>
		<Company>$(Authors)</Company>
		<Description>Description of Fem2Rhino.Grasshopper.Reading</Description>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<EnableNETAnalyzers>False</EnableNETAnalyzers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grasshopper" Version="8.27.26019.16021" />
		<PackageReference Include="RhinoCommon" Version="8.27.26019.16021" />
	</ItemGroup>

	<!-- For Windows only builds -->
	<PropertyGroup Condition="$(TargetFramework.Contains('-windows')) or $(TargetFramework.StartsWith('net4'))">
		<UseWindowsForms>true</UseWindowsForms>
		<UseWpf>true</UseWpf>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Fem2Rhino\Fem2Rhino.Core.csproj" />
		<ProjectReference Include="..\GrasshopperHelper\GrasshopperHelper.csproj" />
		<ProjectReference Include="..\ProxyHelper\ProxyHelper.csproj" />
		<ProjectReference Include="..\Rhino2Fem.Straus.Grasshopper\Rhino2Fem.Grasshopper.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ETABSv1">
			<HintPath>C:\Program Files\Computers and Structures\ETABS 22\ETABSv1.dll</HintPath>
		</Reference>
		<Reference Include="GPCChecker.Concrete">
		  <HintPath>..\..\Checker\GPCChecker.Concrete\bin\Release\netstandard2.0\GPCChecker.Concrete.dll</HintPath>
		</Reference>
		<Reference Include="GPCGeometry">
		  <HintPath>..\..\Geometry\GPCGeometry\bin\Release\netstandard2.0\GPCGeometry.dll</HintPath>
		</Reference>
		<Reference Include="GPCModel">
		  <HintPath>..\..\Model\Model\bin\Release\netstandard2.0\GPCModel.dll</HintPath>
		</Reference>
		<Reference Include="GPCModelData">
		  <HintPath>..\..\Model\ModelData\bin\Release\netstandard2.0\GPCModelData.dll</HintPath>
		</Reference>
		<Reference Include="SAP2000v1">
			<HintPath>C:\Program Files\Computers and Structures\SAP2000 26\SAP2000v1.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="CopyPdbForMonoDebugging" AfterTargets="AfterBuild">
		<!-- Enable debugging in Rhino 6/7 on Mac -->
		<Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFiles="$(TargetDir)$(TargetName).gha.pdb" Condition="$([MSBuild]::IsOSPlatform(OSX)) and $(TargetFramework.StartsWith('net4')) and Exists('$(TargetDir)$(TargetName).pdb')" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="robocopy $(ProjectDir)bin\$(PlatformName)\$(ConfigurationName)\$(TargetFramework) $(SolutionDir)bin\$(TargetFramework) /E /NFL /NDL /NJH /NJS /NC /NS&#xD;&#xA;del /f /q $(ProjectDir)bin\$(PlatformName)\$(ConfigurationName)\$(TargetFramework)&#xA;exit 0" />
	</Target>

</Project>
