<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><EnableDynamicLoading>true</EnableDynamicLoading><UseWindowsForms>true</UseWindowsForms><TargetExt>.gha</TargetExt></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rhino2SAP.Core/Rhino2SAP.Core.csproj" />
    <ProjectReference Include="../Rhino2SAP.Api/Rhino2SAP.Api.csproj" />
    <PackageReference Include="Grasshopper" Version="$(RhinoVersion)" />
    <PackageReference Include="RhinoCommon" Version="$(RhinoVersion)" />
  </ItemGroup>
</Project>
