<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

	
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

	
  <ItemGroup>
	<PackageReference Include="RhinoCommon" Version="7.36.23346.16351" />
	<!--<PackageReference Include="RhinoCommon" Version="8.0.23304.9001" Condition="!$(TargetFramework.StartsWith('net4'))" ExcludeAssets="runtime" />-->
  </ItemGroup>

</Project>
