<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="del $(SolutionDir)bin\$(TargetFramework) /s /q&#xA;exit 0" />
  </Target>

  <ItemGroup>
    <Reference Include="ETABSv1">
      <HintPath>..\..\..\..\..\..\Program Files\Computers and Structures\ETABS 22\ETABSv1.dll</HintPath>
    </Reference>
    <Reference Include="SAP2000v1">
      <HintPath>..\..\..\..\..\..\Program Files\Computers and Structures\SAP2000 26\SAP2000v1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
